verify_signatures: false
gemfile: '.overcommit_gems.rb'

PreCommit:
  RuboCop:
    enabled: true
    on_warn: fail

  HamlLint:
    enabled: true
    on_warn: fail

  CoffeeLint:
    enabled: true
    on_warn: fail
    exclude:
      - 'js/*.coffee'

  JsHint:
    enabled: true
    on_warn: fail
    exclude:
      - 'js/vendor/**/*'
      - 'js/*.js'

  ScssLint:
    enabled: true
    on_warn: fail
    exclude:
      - 'css/*.scss'
      - '_sass/vendor/**/*'

  YamlSyntax:
    enabled: true
    on_warn: fail

  TrailingWhitespace:
    enabled: true
    exclude:
      - '**/*.md'
      - '**/*.markdown'

  ImageOptim:
    enabled: true
    include:
      - '**/*.gif'
      - '**/*.jpeg'
      - '**/*.jpg'
      - '**/*.png'
      - '**/*.webp'
      - '**/*.svg'

  HardTabs:
    enabled: true
