AllCops:
  TargetRubyVersion: 2.1

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 90

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  '{}'
    '%i': '[]'
    '%q': '{}'
    '%Q': '{}'
    '%r': '{}'
    '%s': '{}'
    '%w': '[]'
    '%W': '[]'
    '%x': '{}'

Style/FileName:
  Exclude:
    - '**/.overcommit_gems.rb'
