# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Wild Country Fitness
email: info@wildcountryfitness.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wildcountryfitness.com" # the base hostname & protocol for your site
twitter_username: TODO-twitter
facebook_username: TODO-facebook
timezone: Europe/London
environment: production
safe: true

exclude: ['*.html.haml', 'js/**/*', 'css/**/*', 'Gemfile', 'Gemfile.lock', 'Rakefile', 'Guardfile']

# paginate: 5
# paginate_path: "/our_blog/page:num/"

# Build settings
markdown: kramdown

sass:
  style: :compressed
