# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

### Site settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.wildcountryfitness.com" # the base hostname & protocol for your site

timezone: Europe/London
environment: production

title: Wild Country Fitness

author: Lesley Waldron
description: > # this means to ignore newlines
  Wild Country Fitness offers personal training, running workshops,
  run coaching, wellness retreats, small group training
  and self-care workshops in Bristol and North Somerset.

email: wildcountryfit@gmail.com
twitter: wildcountryfit
facebook: wildcountryfitness
instagram: wildcountryfit

# paginate: 5
# paginate_path: "/our_blog/page:num/"

### Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

exclude:
  - '*.html.haml'
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - Guardfile
  - README.md
  - _config_dev.yml
